### ISSUE TITLE
All properties required option

### ISSUE THREAD

**Issue by marc0l92** [codekie/openapi-examples-validator#169]
Hello,
I would need a new option to make all properties in the openapi schema required:
`--all-properties-required`

This option will not be use to create valid example but to test the backward compatibility of minor versions.
My plan is to create for each minor version a test that requires to provide a maximum JSON.
Then, this json will be tested with the following minor version to make sure the backward compatibility is not violated.

## Example

- V1.0
JSON schema
```yaml
type: object
properties:
  username:
    type: string
```
Maximal example
```json
{"username":"admin"}
```

- V1.1
JSON schema backward compatible
```yaml
type: object
properties:
  username:
    type: string
  password:
    type: string
```
Maximal example
```json
{"username":"admin", "password":"12345"}
```

- V1.2
JSON schema NON backward compatible
```yaml
type: object
properties:
  username:
    type: string
  password:
    type: array
    items:
      type: string
```
Maximal example
```json
{"username":"admin", "password":["12345", "34567"]}
```
</details>

For the version 1.2 I will run the commands:
```
openapi-examples-validator --no-additional-properties --all-properties-required -s api1.2.yaml -e maximalExampleV1.2.json
openapi-examples-validator --no-additional-properties -s api1.2.yaml -e maximalExampleV1.1.json
openapi-examples-validator --no-additional-properties -s api1.2.yaml -e maximalExampleV1.0.json
```
And the test of `maximalExampleV1.1.json` will fail because V1.2 is not backward compatible

Let me know what you think about this new feature.
And if you don't have time to implement it, I can try to do it.
